### ISSUE TITLE
After docker run, knime crash

### ISSUE THREAD

**Issue by Opartl** [DrSnowbird/knime-docker#3]
Hello,
the container does not start. After the docker run, a knime error is thrown. But which is logged in to the container and I do not know what is in it.
![knime-docker](https://user-images.githubusercontent.com/32740205/132093900-b340815e-8b75-4d0d-b4b0-90ed10353978.jpg)

**Comment by zbj3ji** [comment]
I have exactly the same problem. Any idea how to solve it? Any help would be appreciated. Thx

**Comment by DrSnowbird** [comment]
Please do the following to fixed the missing Java Swing library issue:
1. Update this GIT to get latest to use OpenJDK 11 and Ubuntu 20.04 base iimages
2. Build all parent dependent images and then this images LOCALLY due to hub.docker.io not allowing free host anymore. You have to make all these three images build locally (see below Notice).

# NOTICE: Due to docker.hub.io not allowing free hosting anymore, you have to make your local build including the parent images:
- [DrSnowbird/jdk11-mvn-py3](https://github.com/DrSnowbird/jdk11-mvn-py3), [GIT](git@github.com:DrSnowbird/jdk11-mvn-py3.git)
- [DrSnowbird/jdk11-mvn-py3-X11](https://github.com/DrSnowbird/jdk11-mvn-py3-X11), [GIT](git@github.com:DrSnowbird/jdk11-mvn-py3-X11.git)
